### ISSUE TITLE
Please help 

### ISSUE THREAD

**Issue by peterballdd** [Kismuz/btgym#11]
Dear Sir

Could you please help me fix this problem ?

I tried running a3c_sinewave but when i run the last cell (launcher.run())

I found this problem.
[2017-09-04 19:24:45,266] Data file <../examples/data/test_sine_1min_period256_delta0002.csv> not specified / not found.
Process BTgymDataFeedServer-2:1:
Traceback (most recent call last):
  File "/home/balldekdee/btgym/btgym/datafeed.py", line 127, in read_csv
    assert filename and os.path.isfile(filename)
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/balldekdee/btgym/btgym/datafeed.py", line 142, in read_csv
    assert 'episode_dataset' in self.filename
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/balldekdee/btgym/btgym/dataserver.py", line 73, in run
    self.dataset.read_csv()
  File "/home/balldekdee/btgym/btgym/datafeed.py", line 149, in read_csv
    raise FileNotFoundError(msg)
FileNotFoundError: Data file <../examples/data/test_sine_1min_period256_delta0002.csv> not specified / not found.
[2017-09-04 19:24:50,508] Press `Ctrl-C` to stop training and close launcher.

**Comment by Kismuz** [comment]
@peterballdd,
I have put wrong file path here. Corrected. Thank you for pointing that out.

You may either modify code in cell 2, line 76:

`filename='../data/test_sine_1min_period256_delta0002.csv',`

or pull corrected version and reinstall package.
